export const FAMOUS_CITIES = [
    "London",
    "Paris",
    "New York City",
    "Tokyo",
    "Rome",
    "Dubai",
    "Istanbul",
    "Bangkok",
    "Singapore",
    "Sydney",
    "Berlin",
    "Barcelona",
    "Amsterdam",
    "Prague",
    "Cape Town",
    "Rio de Janeiro",
    "Buenos Aires",
    "Shanghai",
    "Hong Kong",
    "Seoul",
    "Los Angeles",
    "Chicago",
    "Toronto",
    "Mexico City",
    "Mumbai",
    "Delhi",
    "Kyoto",
    "Marrakech",
    "Santorini",
    "Venice"
  ];

  export const KELVIN_CELSIUS_DIFFERENT = 273.15